name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '11 * * * *'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/check-and-release.yml@v8.0.0
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "whisparr"
      release_type: "script"
      prerelease: true
      branch: nightly
      dockerhub_user: "thespad"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
      dockerhub_password: ${{ secrets.docker_password }}
