name: Check for base image updates
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/check-baseimage-update.yml@v8.0.3
    with:
      repo_owner: ${{ github.repository_owner }}
      baseimage: "alpine"
      basebranch: "3.19"
      app_name: "whisparr"
      prerelease: true
      branch: nightly
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
