name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-image.yml@v6
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "whisparr"
      release_type: "script"
      dockerhub_user: "thespad"
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
