name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-nightly:
    uses: thespad/actions/.github/workflows/build-split-image.yml@v9.0.4
    with:
      repo_owner: thespad
      app_name: "whisparr"
      release_type: "script"
      dockerhub_user: "thespad"
      target-arch: >-
        ["amd64", "arm64v8"]
      sign_image: false
      branch_name: v2
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
