name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-split-image.yml@v7
    with:
      repo_owner: thespad
      app_name: "whisparr"
      release_type: "script"
      dockerhub_user: "thespad"
      target-arch: >-
        ["amd64", "aarch64", "armhf"]
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
