#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        cd /app/whisparr/bin s6-setuidgid abc /app/whisparr/bin/Whisparr \
        -nobrowser -data=/config
